#!/bin/bash

git checkout starting-lab2
git rebase main
git checkout starting-lab3
git rebase main
git checkout starting-lab4
git rebase main
git checkout starting-lab5
git rebase main
git checkout starting-lab6
git rebase main
git checkout starting-lab7
git rebase main
git checkout starting-lab8
git rebase main
git checkout starting-lab9
git rebase main
git checkout starting-lab10
git rebase main
git checkout starting-lab11
git rebase main
git checkout starting-lab12
git rebase main
git checkout starting-lab13
git rebase main
git checkout starting-lab14
git rebase main
git checkout starting-lab15
git rebase main
git checkout starting-lab16
git rebase main
git checkout starting-lab17
git rebase main
git checkout starting-lab18
git rebase main
git checkout starting-lab19
git rebase main
git checkout starting-lab20-option1
git rebase main
git checkout starting-lab21-option1
git rebase main
git checkout starting-lab20-option2
git rebase main
git checkout starting-lab21-option2
git rebase main
git checkout starting-lab22
git rebase main
git checkout final-solution
git rebase main
git checkout main
